imports:
    - { resource: config_dev.yml }

parameters:
    janus_api_password: password
    minerva_api_password: password
    veritas_api_password: password

framework:
    test: ~
    trusted_proxies: [127.0.0.1]
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db
    orm:
        entity_managers:
            default:
                auto_mapping:         false
                mappings:
                    IceDoctrineMockOfVeritasClientBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  Mapping
                        alias:                ~
                        prefix:               Ice\VeritasClientBundle\Entity
                        is_bundle:            true
                    IceDoctrineMockOfMinervaClientBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  Mapping
                        alias:                ~
                        prefix:               Ice\MinervaClientBundle\Entity
                        is_bundle:            true

ice_mailer:
    file_repository_type: test